// <auto-generated />
using System;
using EduGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduGameProject.Migrations
{
    [DbContext(typeof(EduGameDbContext))]
    [Migration("20260309181406_InitialDbContextWithFluentApi")]
    partial class InitialDbContextWithFluentApi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EduGame.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0)
                        .HasComment("Primary key (auto increment) of Partner for database");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasPrecision(0)
                        .HasColumnType("date")
                        .HasColumnOrder(4);

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(true)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(1)
                        .HasComment("Immutable unique business key for Partner");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(2);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(3);

                    b.Property<string>("Motivation")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(5)
                        .HasComment("Optional cover letter text from the registration form");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(6);

                    b.Property<string>("TypeOfCooperation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("varchar(30)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasAlternateKey("ExternalId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("EduGame.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0)
                        .HasComment("Primary key (auto increment) of Student for database");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasPrecision(0)
                        .HasColumnType("date")
                        .HasColumnOrder(4);

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("varchar(30)")
                        .HasColumnOrder(7);

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(true)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(1)
                        .HasComment("Immutable unique business key for Student");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(2);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(true)
                        .HasColumnType("varchar(15)")
                        .HasColumnOrder(6);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(3);

                    b.Property<string>("Motivation")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(5)
                        .HasComment("Optional cover letter text from the registration form");

                    b.HasKey("Id");

                    b.HasAlternateKey("ExternalId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EduGame.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0)
                        .HasComment("Primary key (auto increment) of Teacher for database");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasPrecision(0)
                        .HasColumnType("date")
                        .HasColumnOrder(4);

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(true)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(1)
                        .HasComment("Immutable unique business key for Teacher");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(2);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(true)
                        .HasColumnType("varchar(15)")
                        .HasColumnOrder(6);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(3);

                    b.Property<string>("Motivation")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(5)
                        .HasComment("Optional cover letter text from the registration form");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasAlternateKey("ExternalId");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
